server:
  port: 9090
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
logging.level:
  org.springframework: error
  org.hibernate.SQL: error
  com.lcw: debug


#=============================#
#===== Database Settings =====#
#=============================#
spring.jpa:
  show-sql: false
  database-platform: org.hibernate.dialect.MySQLDialect
spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/bidding_im?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
  username: root
  password: one
  driver-class-name: com.mysql.jdbc.Driver
  type: com.alibaba.druid.pool.DruidDataSource
  druid:
    initial-size: 3
    max-active: 50
    min-idle: 2
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x' FROM DUAL

#=============================#
#=====   Redis Settings  =====#
#=============================#
spring.redis:
  database: 0
  host: 127.0.0.1
  port: 6379
  password:
  lettuce.pool:
    max-active: 20
    max-wait: -1ms
    max-idle: 8
    min-idle: 0